kazupon/args-tokens

.github/workflows/release.yml, jsr.json, scripts/release.sh, src/index.test.ts, tsconfig.json
=> feat: support jsr

src/index.ts
=> fix: improve api docs

jsr.json
=> fix: wrong exports for jsr

src/index.ts, src/parse.ts
=> fix: wrong type exporting

src/parse.test.ts, src/resolver.test.ts, src/resolver.ts, tsconfig.cjs.json, tsconfig.esm.json
=> feat: support capture positional arg as option value

src/index.ts
=> feat: export `ArgOptions`

src/index.ts
=> feat: export `ArgValues`

package.json
=> fix: module type

.github/workflows/ci.yml, .github/workflows/nightly-release.yml, .github/workflows/release.yml, package.json
=> breaking: drop node v18

src/parse.ts, src/resolver.test.ts, src/resolver.ts
=> feat: support aggregate validation errors

src/__snapshots__/resolver.test.ts.snap, src/parse.ts, src/resolver.test.ts, src/resolver.ts
=> feat: resolve with validation error

src/resolver.test.ts, src/resolver.ts
=> fix: more safe manuperation for option values

src/resolver.ts
=> fix: tweak validation error message format

src/resolver.ts
=> feat: support `description` field for `ArgOptionSchema`

src/index.ts, src/resolver.test.ts, src/resolver.ts
=> feat: support option resolve error type

src/parse.ts, src/parser.ts, src/resolver.test.ts, src/resolver.ts
=> feat: support options grouping

src/index.ts, src/parse.test.ts, src/resolver.test.ts, src/resolver.ts
=> fix: not handle resolved value arguments as positionals

src/resolver.test-d.ts, src/resolver.test.ts, src/resolver.ts
=> feat: support enum type

src/parse.test.ts, src/parse.ts, src/resolver.test.ts, src/resolver.ts
=> feat: support flag option prefixed with `--no-` to nagetive

src/resolver.test.ts, src/resolver.ts
=> fix: cannot resolve multiple long option value

src/resolver.test-d.ts, src/resolver.ts
related https://github.com/kazupon/gunshi/issues/103
=> fix: cannot resolve choices type error for readonly string array

deno.json, package.json
=> fix: type check error on deno check
